apiVersion: apps/v1
kind: Deployment
metadata:
  name: avs-api-deployment
  labels:
    app: avs-aip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: avs-api
  template:
    metadata:
      labels:
        app: avs-api
    spec:
      containers:
        - name: avs-api
          image: astrovikingsolutions/api:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: avs-lb
spec:
  selector:
    app: avs-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
